SPELLS = [ {'castTime': 1, 'hasTarget': False, 'manaCost': 4, 'name': 'Create Food'},
  {'castTime': 1, 'hasTarget': False, 'manaCost': 4, 'name': 'Reactive Armor'},
  {'castTime': 1, 'hasTarget': True, 'manaCost': 4, 'name': 'Clumsy'},
  {'castTime': 1, 'hasTarget': True, 'manaCost': 4, 'name': 'Feeblemind'},
  {'castTime': 1, 'hasTarget': True, 'manaCost': 4, 'name': 'Heal'},
  {'castTime': 1, 'hasTarget': True, 'manaCost': 4, 'name': 'Magic Arrow'},
  {'castTime': 1, 'hasTarget': False, 'manaCost': 4, 'name': 'Night Sight'},
  {'castTime': 1, 'hasTarget': True, 'manaCost': 4, 'name': 'Weaken'},
  {'castTime': 1.25, 'hasTarget': True, 'manaCost': 6, 'name': 'Agility'},
  {'castTime': 1.25, 'hasTarget': True, 'manaCost': 6, 'name': 'Cunning'},
  {'castTime': 1.25, 'hasTarget': True, 'manaCost': 6, 'name': 'Cure'},
  {'castTime': 1.25, 'hasTarget': True, 'manaCost': 6, 'name': 'Harm'},
  {'castTime': 1.25, 'hasTarget': True, 'manaCost': 6, 'name': 'Magic Trap'},
  {'castTime': 1.25, 'hasTarget': True, 'manaCost': 6, 'name': 'Remove Trap'},
  {'castTime': 1.25, 'hasTarget': False, 'manaCost': 6, 'name': 'Protection'},
  {'castTime': 1.25, 'hasTarget': True, 'manaCost': 6, 'name': 'Strength'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 9, 'name': 'Bless'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 9, 'name': 'Fireball'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 9, 'name': 'Magic Lock'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 9, 'name': 'Poison'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 9, 'name': 'Telekinesis'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 9, 'name': 'Teleport'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 9, 'name': 'Unlock'},
  { 'castTime': 1.75,
    'hasTarget': True,
    'manaCost': 11,
    'name': 'Wall of Stone'},
  {'castTime': 1.75, 'hasTarget': False, 'manaCost': 11, 'name': 'Arch Cure'},
  { 'castTime': 1.75,
    'hasTarget': False,
    'manaCost': 11,
    'name': 'Arch Protection'},
  {'castTime': 1.75, 'hasTarget': True, 'manaCost': 11, 'name': 'Curse'},
  {'castTime': 1.75, 'hasTarget': False, 'manaCost': 11, 'name': 'Fire Field'},
  {'castTime': 1.75, 'hasTarget': True, 'manaCost': 11, 'name': 'Greater Heal'},
  {'castTime': 1.75, 'hasTarget': True, 'manaCost': 11, 'name': 'Lightning'},
  {'castTime': 1.75, 'hasTarget': True, 'manaCost': 11, 'name': 'Mana Drain'},
  {'castTime': 1.75, 'hasTarget': False, 'manaCost': 11, 'name': 'Recall'},
  {'castTime': 5.5, 'hasTarget': True, 'manaCost': 14, 'name': 'Blade Spirits'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 14, 'name': 'Dispel Field'},
  {'castTime': 1.5, 'hasTarget': False, 'manaCost': 14, 'name': 'Incognito'},
  { 'castTime': 1.5,
    'hasTarget': False,
    'manaCost': 14,
    'name': 'Magic Reflection'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 14, 'name': 'Mind Blast'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 14, 'name': 'Paralyze'},
  {'castTime': 1.5, 'hasTarget': False, 'manaCost': 14, 'name': 'Poison Field'},
  { 'castTime': 9,
    'hasTarget': False,
    'manaCost': 14,
    'name': 'Summon Creature'},
  {'castTime': 1.75, 'hasTarget': True, 'manaCost': 20, 'name': 'Dispel'},
  {'castTime': 1.75, 'hasTarget': True, 'manaCost': 20, 'name': 'Energy Bolt'},
  {'castTime': 1.75, 'hasTarget': True, 'manaCost': 20, 'name': 'Explosion'},
  { 'castTime': 1.75,
    'hasTarget': False,
    'manaCost': 20,
    'name': 'Invisibility'},
  {'castTime': 1.75, 'hasTarget': False, 'manaCost': 20, 'name': 'Mark'},
  {'castTime': 1.75, 'hasTarget': False, 'manaCost': 20, 'name': 'Mass Curse'},
  { 'castTime': 1.75,
    'hasTarget': False,
    'manaCost': 20,
    'name': 'Paralyze Field'},
  {'castTime': 1.75, 'hasTarget': False, 'manaCost': 20, 'name': 'Reveal'},
  { 'castTime': 2,
    'hasTarget': False,
    'manaCost': 40,
    'name': 'Chain Lightning'},
  {'castTime': 2, 'hasTarget': False, 'manaCost': 40, 'name': 'Energy Field'},
  {'castTime': 2, 'hasTarget': True, 'manaCost': 40, 'name': 'Flamestrike'},
  {'castTime': 2, 'hasTarget': False, 'manaCost': 40, 'name': 'Gate Travel'},
  {'castTime': 2, 'hasTarget': True, 'manaCost': 40, 'name': 'Mana Vampire'},
  {'castTime': 2, 'hasTarget': False, 'manaCost': 40, 'name': 'Mass Dispel'},
  {'castTime': 2, 'hasTarget': False, 'manaCost': 40, 'name': 'Meteor Swarm'},
  {'castTime': 2, 'hasTarget': False, 'manaCost': 40, 'name': 'Polymorph'},
  {'castTime': 2, 'hasTarget': False, 'manaCost': 40, 'name': 'Earthquake'},
  { 'castTime': 2.25,
    'hasTarget': True,
    'manaCost': 50,
    'name': 'Energy Vortex'},
  {'castTime': 2.25, 'hasTarget': True, 'manaCost': 50, 'name': 'Resurrection'},
  { 'castTime': 2.25,
    'hasTarget': False,
    'manaCost': 50,
    'name': 'Air Elemental'},
  { 'castTime': 2.25,
    'hasTarget': False,
    'manaCost': 50,
    'name': 'Air Elemental'},
  { 'castTime': 2.25,
    'hasTarget': False,
    'manaCost': 50,
    'name': 'Summon Daemon'},
  { 'castTime': 2.25,
    'hasTarget': False,
    'manaCost': 50,
    'name': 'Earth Elemental'},
  { 'castTime': 2.25,
    'hasTarget': False,
    'manaCost': 50,
    'name': 'Fire Elemental'},
  { 'castTime': 2.25,
    'hasTarget': False,
    'manaCost': 50,
    'name': 'Water Elemental'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 14, 'name': 'Animate Dead'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 9, 'name': 'Blood Oath'},
  {'castTime': 1.5, 'hasTarget': False, 'manaCost': 11, 'name': 'Corpse Skin'},
  {'castTime': 0.75, 'hasTarget': False, 'manaCost': 7, 'name': 'Curse Weapon'},
  {'castTime': 0.75, 'hasTarget': False, 'manaCost': 7, 'name': 'Evil Omen'},
  {'castTime': 2, 'hasTarget': False, 'manaCost': 11, 'name': 'Horrific Beast'},
  {'castTime': 2, 'hasTarget': False, 'manaCost': 23, 'name': 'Lich Form'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 17, 'name': 'Mind Rot'},
  {'castTime': 1, 'hasTarget': True, 'manaCost': 10, 'name': 'Pain Spike'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 17, 'name': 'Poison Strike'},
  {'castTime': 2, 'hasTarget': True, 'manaCost': 23, 'name': 'Strangle'},
  {'castTime': 2, 'hasTarget': True, 'manaCost': 24, 'name': 'Summon Familiar'},
  { 'castTime': 2,
    'hasTarget': False,
    'manaCost': 24,
    'name': 'Vampiric Embrace'},
  { 'castTime': 2,
    'hasTarget': False,
    'manaCost': 20,
    'name': 'Vengeful Spirit'},
  {'castTime': 1.5, 'hasTarget': False, 'manaCost': 20, 'name': 'Wither'},
  {'castTime': 2, 'hasTarget': False, 'manaCost': 17, 'name': 'Wraith Form'},
  {'castTime': 2, 'hasTarget': True, 'manaCost': 17, 'name': 'Exorcism'},
  {'castTime': 1, 'hasTarget': True, 'manaCost': 10, 'name': 'Cleanse by Fire'},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 10, 'name': 'Close Wounds'},
  { 'castTime': 0.5,
    'hasTarget': False,
    'manaCost': 7,
    'name': 'Consecrate Weapon'},
  {'castTime': 0.25, 'hasTarget': False, 'manaCost': 5, 'name': 'Dispel Evil'},
  {'castTime': 1, 'hasTarget': False, 'manaCost': 9, 'name': 'Divine Fury'},
  {'castTime': 0.5, 'hasTarget': False, 'manaCost': 11, 'name': 'Enemy of One'},
  {'castTime': 1.75, 'hasTarget': False, 'manaCost': 14, 'name': 'Holy Light'},
  { 'castTime': 1.5,
    'hasTarget': False,
    'manaCost': 20,
    'name': 'Noble Sacrifice'},
  {'castTime': 1.5, 'hasTarget': False, 'manaCost': 20, 'name': 'Remove Curse'},
  { 'castTime': 1.5,
    'hasTarget': False,
    'manaCost': 20,
    'name': 'Sacred Journey'},
  { 'castTime': 0.5,
    'hasTarget': False,
    'manaCost': 24,
    'name': 'Arcane Circle'},
  {'castTime': 3, 'hasTarget': True, 'manaCost': 20, 'name': 'Gift of Renewal'},
  { 'castTime': 1,
    'hasTarget': False,
    'manaCost': 10,
    'name': 'Immolating Weapon'},
  {'castTime': 1, 'hasTarget': False, 'manaCost': 11, 'name': 'Attune Weapon'},
  {'castTime': 1.5, 'hasTarget': False, 'manaCost': 14, 'name': 'Thunderstorm'},
  { 'castTime': 1.5,
    'hasTarget': False,
    'manaCost': 24,
    'name': "Nature's Fury"},
  {'castTime': 1.5, 'hasTarget': True, 'manaCost': 20, 'name': 'Summon Fey'},
  {'castTime': 2, 'hasTarget': True, 'manaCost': 24, 'name': 'Summon Fiend'},
  {'castTime': 2.5, 'hasTarget': False, 'manaCost': 24, 'name': 'Reaper Form'},
  {'castTime': 2.5, 'hasTarget': False, 'manaCost': 32, 'name': 'Wildfire'},
  { 'castTime': 3,
    'hasTarget': False,
    'manaCost': 32,
    'name': 'Essence of Wind'},
  {'castTime': 3, 'hasTarget': False, 'manaCost': 32, 'name': 'Dryad Allure'},
  { 'castTime': 3.5,
    'hasTarget': False,
    'manaCost': 40,
    'name': 'Ethereal Voyage'},
  {'castTime': 3.5, 'hasTarget': True, 'manaCost': 40, 'name': 'Word of Death'},
  {'castTime': 4, 'hasTarget': True, 'manaCost': 40, 'name': 'Gift of Life'},
  { 'castTime': 3,
    'hasTarget': False,
    'manaCost': 24,
    'name': 'Arcane Empowerment'},
  {'castTime': 1, 'hasTarget': True, 'manaCost': 9, 'name': 'Nether Bolt'},
  { 'castTime': 5.5,
    'hasTarget': False,
    'manaCost': 12,
    'name': 'Healing Stone'},
  {'castTime': 1.5, 'hasTarget': False, 'manaCost': 14, 'name': 'Purge Magic'},
  {'castTime': 0.75, 'hasTarget': False, 'manaCost': 10, 'name': 'Enchant'},
  {'castTime': 1.75, 'hasTarget': False, 'manaCost': 17, 'name': 'Sleep'},
  { 'castTime': 1.75,
    'hasTarget': False,
    'manaCost': 17,
    'name': 'Eagle Strike'},
  { 'castTime': 2,
    'hasTarget': False,
    'manaCost': 24,
    'name': 'Animated Weapon'},
  {'castTime': 2, 'hasTarget': False, 'manaCost': 20, 'name': 'Stone Form'},
  { 'castTime': 5.5,
    'hasTarget': False,
    'manaCost': 50,
    'name': 'Spell Trigger'},
  {'castTime': 2, 'hasTarget': False, 'manaCost': 24, 'name': 'Mass Sleep'},
  { 'castTime': 2,
    'hasTarget': False,
    'manaCost': 24,
    'name': 'Cleansing Winds'},
  {'castTime': 2.75, 'hasTarget': False, 'manaCost': 30, 'name': 'Bombard'},
  {'castTime': 2.5, 'hasTarget': False, 'manaCost': 24, 'name': 'Spell Plague'},
  {'castTime': 2.5, 'hasTarget': False, 'manaCost': 28, 'name': 'Hail Storm'},
  { 'castTime': 2.75,
    'hasTarget': True,
    'manaCost': 30,
    'name': 'Nether Cyclone'},
  { 'castTime': 2.75,
    'hasTarget': True,
    'manaCost': 40,
    'name': 'Rising Colossus'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 4, 'name': 'Inspire'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 4, 'name': 'Invigorate'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 4, 'name': 'Resilience'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 4, 'name': 'Perseverance'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 4, 'name': 'Tribulation'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 4, 'name': 'Despair'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 6, 'name': 'Death Ray'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 6, 'name': 'Ethereal Burst'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 6, 'name': 'Nether Blast'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 4, 'name': 'Mystic Weapon'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 6, 'name': 'Command Undead'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 6, 'name': 'Conduit'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 6, 'name': 'Mana Shield'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 6, 'name': 'Summon Reaper'},
  { 'castTime': 0,
    'hasTarget': False,
    'manaCost': 3,
    'name': 'Honorable Execution'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 3, 'name': 'Counter Attack'},
  { 'castTime': 0,
    'hasTarget': False,
    'manaCost': 3,
    'name': 'Lightning Strike'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 3, 'name': 'Confidence'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 3, 'name': 'Evasion'},
  {'castTime': 0, 'hasTarget': False, 'manaCost': 3, 'name': 'Momentum Strike'}]